### ISSUE TITLE
Add dedicated template var to indicate we are on the rules page

### ISSUE THREAD

**Issue by PayBas** [phpbb-extensions/boardrules#223]
We do this for most important pages, like so: https://github.com/phpbb/phpbb/blob/develop/phpBB/viewtopic.php#L717
and https://github.com/phpbb/phpbb/blob/develop/phpBB/ucp.php#L39

I suggest we do the same here:
https://github.com/phpbb-extensions/boardrules/blob/master/controller/main_controller.php#L152
Something like: `S_IN_RULES`

This will come in handy for style authors who use it to highlight icons/status/whatever.

**Comment by VSEphpbb** [comment]
I would prefer `S_BOARD_RULES`

**Comment by PayBas** [comment]
That's fine

**Comment by VSEphpbb** [comment]
I was gonna say you could just use `BOARDRULES_EXPLAIN` but why do you need to test if it is defined?

**Comment by PayBas** [comment]
It's not completely necessary, but Twig has this functionality, so might as well use it.

Regardless, having a dedicated template var for this would look better.

**Comment by VSEphpbb** [comment]
Submit a PR :+1:

**Comment by PayBas** [comment]
https://github.com/phpbb-extensions/boardrules/pull/224
