### ISSUE TITLE
Use sql_freeresult after sql queries

### ISSUE THREAD

**Issue by marc1706** [phpbb-extensions/boardrules#229]
At least the following lines do not use sql_freeresult:

- https://github.com/phpbb-extensions/boardrules/blob/master/migrations/v10x/m11_notification_type_update.php#L29
- https://github.com/phpbb-extensions/boardrules/blob/master/migrations/v10x/m7_sample_rule_data.php#L28
- https://github.com/phpbb-extensions/boardrules/blob/master/tests/operators/rule_operator_change_parent_test.php#L71
- https://github.com/phpbb-extensions/boardrules/blob/master/tests/operators/rule_operator_delete_rule_test.php#L82
- https://github.com/phpbb-extensions/boardrules/blob/master/tests/operators/rule_operator_move_test.php#L148

**Comment by VSEphpbb** [comment]
Thanks. @rxu or @ForumHulp if either of you would like to take this, that would be great.

**Comment by DavidIQ** [comment]
P.S. whoever decides to do this set yourself as the "Assignee" on the right.

**Comment by ForumHulp** [comment]
OK for me end f the week

**Comment by rxu** [comment]
For me either. It's pretty easy job so can be done fast.

**Comment by VSEphpbb** [comment]
@rxu if you can do it sooner, might as well be you. Also try to see if there are any other instances where it's not used that Marc did not mention above.

**Comment by rxu** [comment]
Searced through the files and found 6 files are missing sql_freeresult, 4 of them are tests.

**Comment by rxu** [comment]
Btw, it seems that I can't assign issues here, even to myself.

**Comment by DavidIQ** [comment]
Should be able to now.

**Comment by rxu** [comment]
Now it's ok, thanks.
