### ISSUE TITLE
Require phing as a dependency for -dev

### ISSUE THREAD

**Issue by n-aleha** [phpbb-extensions/boardrules#242]
Now that a build script has been added, as per our discussion on irc with MichaelC my question is if we should require phing as a dependency for -dev.

**Comment by VSEphpbb** [comment]
No, not needed. As this is an extension to phpBB, there already is phing available in the phpBB repository. The build script is only meant to be used by developers, so they should use the copy of phing already available in phpBB's vendor dir. Also, the build script is only intended to be sued by the official extension development team when preparing releases.
